### ISSUE TITLE
Importing default prevents the use of the Interval type unless also imported

### ISSUE THREAD

**Issue by VolatilePulse** [mauriciopoppe/interval-arithmetic#18]
While a minor inconvenience, Typescript prevents the use of type `Interval` on variables when using `import **IA** from 'interval-arithmetic'`. This results in an import statement that looks like `import **IA**, { Interval } from 'interval-arithmetic'`. As IA is just an alias for Interval and the default export, I'm not sure why it doesn't specifically allow it. I just did some additional research in a previous project that used interval-arithmetic extensively and found that this hasn't always been the case (v0.6.10). I'm not sure if this is an issue due to the conversion to Typescript, or an intentional change that you made, but really miss that convenience.

Another gripe that I currently have that I didn't have previously was that in order to create a new interval, the keyword `new` wasn't needed. I verified it with some old code and also checked the `readme.md` and it's still listed as supposedly being supported. Our previous import statement looked like `import IA from 'interval-arithmetic'` and we were able to use intervals just as you show in the readme, as so: 
```js
const x = Interval(0, 1);
Interval.add(
  Interval.sin(Interval.exp(x)),
  Interval.sub(
    Interval.tan(x),
    Interval.mul(
      Interval.div(Interval.ONE, Interval.cos(Interval.PI)),
      Interval.pow(Interval(1, 3), 2)
    )
  )
);
``` 
And code from an old project:
```ts
export function intervalFromDecimal(value: number, places: number): Interval {
   const offset = IA.mul(IA(5), IA.pow(IA(10), IA(-(places + 1))));
   return IA().halfOpenRight(floatRange(value - offset.hi).lo, floatRange(value + offset.hi).hi);
}
```
```ts
describe('intFromRange', () => {
   it('[-0.5,4.5] should contain [0,1,2,3,4]', () => {
      expect(Array.from(intFromRange(IA(-0.5, 4.5)))).to.deep.equal([0, 1, 2, 3, 4]);
   });
});
```

Is it possible to bring these mechanics back, or is there something that I'm missing on my end that was set up in our old project and isn't working as expected?

**Comment by mauriciopoppe** [comment]
Thanks for checking this, indeed the `new` code that was there before the port to TS is still there but after transpiling looks different, I've added some workaround to make the class callable without new and also made sure that the default export contains all the methods too.

It should be fixed in https://github.com/mauriciopoppe/interval-arithmetic/releases/tag/v1.0.2

**Comment by VolatilePulse** [comment]
I really appreciate the quick responses from you. I'm afraid it looks like it hasn't quite compiled correctly. After installing the module, this is all that is contained within: 
![image](https://user-images.githubusercontent.com/6995232/86518073-572a0000-bdfc-11ea-8f14-5b2819e6eced.png)

**Comment by VolatilePulse** [comment]
Disregard the last message. That does appear to have been resolved on my end some how after reinstalling it. I'm still unable to use the type when importing unless I import the type separately though. Not requiring `new` does work as expected though.

**Comment by mauriciopoppe** [comment]
I updated the tests to use:

```
import Interval from 'interval-arithmetic'
```

That's the default import and it should have all the existing functionality of versions < 1, there's the named `Inteval` import too e.g. `import All, { Interval }  from 'interval-arithmetic'`

**Comment by VolatilePulse** [comment]
With the following code:
```ts
import IA, { Interval } from 'interval-arithmetic';
```
Results in:
```
import Interval
Module '"../node_modules/interval-arithmetic/lib"' has no exported member 'Interval'. Did you mean 'isInterval'?ts(2724)
utils.d.ts(25, 25): 'isInterval' is declared here.
```

I was hoping to avoid having to also include the Interval type just so that I could have type information on variables, but it it's not possible otherwise, that's fine. However, this is a step back from how it worked previously as I can no longer import the `Interval` type from the library.

**Comment by mauriciopoppe** [comment]
Extending the default class `Interval` with static methods outside it is painful, I've updated the import to be: 

```
import IA, { Interval } from 'interval-arithmetic';
```

v1.0.3 had a bug here and was exporting something else, I'll publish a new version that fulfills the import above.

In your method signature you might need to try with both IA and Interval

I've published v1.0.4

**Comment by VolatilePulse** [comment]
I'm content with using both, just would have preferred not to. As far as v1.0.4 is concerned, I'm still getting an error with the above posted code (and importing both the default and Interval):
```ts
export function* intFromRange(interval: Interval, fn?: (value: number) => number): Generator<number> {
```
```
any
'Interval' refers to a value, but is being used as a type here. Did you mean 'typeof Interval'?ts(2749)
```

This error is specifically on the `Interval` type for the variable named `interval`. This is the same error that I get if I use the default export as the type:
```ts
export function* intFromRange(interval: IA, fn?: (value: number) => number): Generator<number> {
```
```
any
'IA' refers to a value, but is being used as a type here. Did you mean 'typeof IA'?ts(2749)
```

I'm really sorry for making this such a headache for you. I definitely appreciate the patience with me.

**Comment by mauriciopoppe** [comment]
I've published a new version v1.0.5 that hopefully works, I've tried it here https://codesandbox.io/s/wonderful-black-yzjzd?file=/src/index.ts

**Comment by VolatilePulse** [comment]
Everything appears to be working as expected. Thank you again for your patience and making those changes!
